# Configuration file for ShoreFor_Paris2024

##############
# Study info #
##############
case:
  study: 'duck'
  # 1 for shoreline, 2 for bars
  evolution: 1

###############
# Input files #
###############

input_files:
  shoreline_file: './examples/shoreline_duck_2000-2022.csv'
  waves_file: './examples/forcing_duck_daily_8m_1990-2022.dat'

################
# Dakota setup #
################

# Optimization
optimization:
  dakota: 2 #1 if you want to use dakota / 2 if you already know the parameters
  # If 2, set the parameters values:
  b: -0.00305 
  c: 0.0021 
  phi: 189

dakota_params:
  # b in m/days
  # c in m^1.5 days^-1 W-0.5
  # phi in days
  b_min: -0.01
  b_max: 0.01
  c_min: 0.01
  c_max: 0.1
  phi_min: 300
  phi_max: 400

#######################
# Begin and end times #
#######################

calibration:
  time_initial: '2000-02-01'
  time_final: '2012-09-01'

future:
  # Extrapolate the shoreline ? 1: yes, 2: no
  extrapolate: 2
  # initial time for the extrapolation
  begin_future_time: '2019-02-15'
  final_future_time: '2020-12-06'
