# Configuration file for ShoreFor

##############
# Study info #
##############
case:
  study: 'duck2000-2022'
  # 1 for shoreline, 2 for bars
  evolution: 1

###############
# Input files #
###############

input_files:
  #shoreline_file: './examples/Shoreline_1.5.dat'
  #waves_file: './examples/TrucVert_Forcing.dat'
  shoreline_file: './../../data/shoreline/shoreline_duck_2000-2022.csv'
  #shoreline_file: './../../data/barres/evolution_bars_frag_thornton_2000-2022.csv'
  #shoreline_file: './fichiers_barres/evolution_bars_frag_0-180_2000-2018.csv'
  waves_file: './../../data/waves/forcing_duck_daily_8m_1990-2022.dat'
  #waves_file: './examples/forcing_duck_datenum_test_daily.dat'

################
# Dakota setup #
################

# Optimization
optimization:
  dakota: 2 #1 if you want to use dakota / 2 if you already know the parameters
  # If 2, set the parameters values:
  # bars
  #b: 0.0002 
  #c: 0.04 
  #phi: 100
  # Bars 'thornton if bars'
  #b: 0.0025 
  #c: -0.08
  #phi: 270
  # shoreline
  #b: -0.003 #0.002
  #c: 0.003 #0.006
  #phi: 250 #190
  #b: -0.004
  #c: 0.005
  #phi: 150
  # Compa Splinter
  #b: 0.0082
  #c: 0.00432
  #phi: 250
  # TV
  #b: 0.00034
  #c: 0.0095
  #phi: 213
  # Duck Barres 2000-2022
  #b: 0.0025
  #c: -0.08
  #phi: 270
  # SHORELINE DUCK
  # 2000-2012 Dakota
  #b: -0.003052879252
  #c: 0.0021033644528
  #phi: 188.94867715
  # 2000-2012 main
  b: -0.00305
  c: 0.0021
  phi: 189
  # 2000-2006 Dakota
  #b: -0.00025522253022
  #c: 0.0021899738164
  #phi: 177.81036346
  # 2006-2012 Dakota
  #b: -0.0074522471509
  #c: 0.002032853804
  #phi: 155.43415535
  # BARS DUCK
  # 2000-2012 Dakota
  #b: -0.0099124170374 
  #c: -0.041166420824
  #phi: 389.70719217
  # 2000-2006 Dakota
  #b: -0.0097887968644 
  #c: -0.052513605873
  #phi: 379.14818056
  # 2006-2012 Dakota
  #b: 0.0062135989481
  #c: 0.011591849167
  #phi: 150.53302269

dakota_params:
  # b in m/days
  # c in m^1.5 days^-1 W-0.5
  # phi in days
  b_min: -0.01
  b_max: 0.01
  c_min: 0.01 #-0.1 #0.002
  c_max: 0.1 #-0.002 #0.01
  phi_min: 300
  phi_max: 400


#######################
# Begin and end times #
#######################
# It's better if there is shoreline data for the initial time of the extrapolation

calibration:
  #time_initial: '2016-01-14'
  #time_final: '2018-12-13'
  #time_initial: '2000-02-01'
  #time_final: '2012-09-28'
  # Splinter Duck
  #time_initial: '2000-03-15'
  #time_final: '2006-12-07'
  #time_initial: '2005-01-01'
  #time_final: '2013-01-01'
  # Duck 2000-2012
  #time_initial: '2000-02-01'
  #time_final: '2012-09-01'
  # Duck 2000-2006
  time_initial: '2000-02-01'
  time_final: '2006-09-01'
  # Duck 2006-2012
  #time_initial: '2006-02-01'
  #time_final: '2012-09-01'
  # Duck 2017-2019
  #time_initial: '2017-01-01'
  #time_final: '2019-02-01'

future:
  # Extrapolate the shoreline ? 1: yes, 2: no
  extrapolate: 1
  # initial time for the extrapolation
  # Duck 2019
  #begin_future_time: '2019-02-15'
  #final_future_time: '2019-12-06'
  # Duck 2020
  begin_future_time: '2019-02-15'
  final_future_time: '2020-12-06'
  # Duck 2016-2019
  #begin_future_time: '2000-02-01'
  #begin_future_time: '2016-12-01'
  #final_future_time: '2018-06-30'
  #final_future_time: '2019-12-06'
